spring.application.name=Interior Design Planner
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.config.import=optional:./local.properties
springdoc.swagger-ui.path=/swagger-ui-interior-design-planner.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.default-models-expand-depth=-1

jwt.secret.key=${JWT_SECRET}
jwt.expiration.time=${JWT_EXPIRATION}
jwt.header=${JWT_HEADER}